---
title: "Final-Project-Group3"
author: "John M. Musah & Alan R. Galloway"
date: "11/1/2021"
output: html_document
---



#LINEAR REGRESSION


```{r setup, include=FALSE}
#' @title Least Square Estimator-group3 
#'
#' @description We create a function of the OLS estimator of the coefficients called beta_hats. 
#' @param Dependent A \code{vector} with the values for the dependent variable (or outcome variable).
#' @param Independent A \code{matrix} with the values for the independent variable.
#' @return A \code{numeric}.
#' @author John M. Musah & Alan R. Galloway
#' @importFrom 
#' @export
#' @examples
#' Using data("USArrests")
#' coeff_lm(USArrests$Murder,USArrests$UrbanPop)


coeff_beta <- function (Dependent, Independent) {
  
  #-------------------------------- preamble -------------------------------------
  # in case user gets something that is not a vector for 'Dependent'
  #  or a matrix for 'Independent', coerce data:
 Dependent <- as.matrix(Dependent)
 Independent <- as.matrix(cbind(1,Independent))
  
 #-------------------------------------------------------------------------------
  # Define number of observation and dimension:
  n <- length(Dependent)
  p <- dim(Independent)[2]
  degrees_freedom <- n - p
  #-------------------------------------------------------------------------------
  # check and warnings:
  if(n != dim(Independent)[1])
    stop("Can you check the correspondence between x and y values? It seems we do not have proper pairs! If in doubt, check the documentation using ?coeff_least_sq")
  #-------------------------------------------------------------------------------
  
  beta <- solve(t(Independent)%*%Independent)%*%t(Independent)%*%Dependent
  
#  return(beta)
  ## calculate residuals
res <- as.matrix(Dependent - Independent%*%beta)
## calculate the Variance-Covariance matrix (VCV)
#  VCV = (1/(n-k))res'res(X'X)^(-1)
VCV <- 1/(n-p) * as.numeric(t(res)%*%res) * solve(t(Independent)%*%Independent)
 
## calculate standard errors (se) of coefficients
se <- sqrt(diag(VCV))


 
## combine all necessary information
return (as.data.frame(cbind(c("(Intercept)","Independent"),
                                beta,se)))

 
}

coeff_beta(USArrests$Murder,USArrests$UrbanPop)

```






```{r}
#' @title Linear Model Function-group3
#'
#' @description We create a function of the OLS estimator of the coefficients called beta_hats. 
#' @param Dependent A \code{vector} with the values for the dependent variable (or outcome variable).
#' @param Independent A \code{matrix} with the values for the independent variable.
#' @param Beta A \code{matrix} that can be calculated using \code{coeff_lm} function.!
#' @param alpha A \code{numeric} (double) that sets the alpha coefficient to be used. Has to be between 0 and 1.
#' @param method A \code{string} that defines the method used. Options are "Asymptotic" and "Bootstrap", accepts minor misspellings with a warning - which can be both good and bad.
#' @return A \code{list} containing the following attributes:
#' \describe{
#'      \item{beta}{Estimated coefficients, Linear Regression Model.}
#'      \item{sigma2}{explanation}
#'      \item{variance_beta}{explanation}
#'      \item{ci}{explanation}
#' }
#' @author John M. Musah & Alan R. Galloway
#' @importFrom 
#' @export
#' @examples
#' Using data("USArrests")
#' coeff_lm(USArrests$Murder,USArrests$UrbanPop)

coeff_ci <- function (Dependent, Independent, alpha = 0.05, method = "Asymptotic") {
  
  #--------------------------------------------------------------------------
  #-------------------------------- preamble --------------------------------
  
  # in case user gets something that is not a vector for 'Dependent'
  #  or a matrix for 'Independent', coerce data:
  #  
 Dependent <- as.matrix(Dependent)
 Independent <- as.matrix(cbind(1,Independent))
  #--------------------------------------------------------------------------
  # Define number of observation and dimension:
  n <- length(Dependent)
  p <- dim(Independent)[2]
  degrees_freedom <- n - p
  ci_beta <- rep(NA, p)
  size <- 1000
  beta <- coeff_beta(Dependent, Independent)
  #--------------------------------------------------------------------------
  # check and warnings:
  # 
  if(n != dim(Independent)[1])
    
    stop("Can you check the correspondence between x and y values? It seems we do not have proper pairs! If in doubt, check the documentation using ?coeff_least_sq")
  #--------------------------------------------------------------------------
  # feedback for alpha value:
  # 
  if(alpha >= 1 | alpha <= 0) 
    
    stop("The alpha here has to be somewhere between 0 and 1... For biological applications we usually aim for 0.05, for example. If in doubt, check the documentation using ?coeff_lm")
  #--------------------------------------------------------------------------
  # feedback for method: try to fix any misspelling of 'method' argument:
  # 
  method_check_a <- stringsim("Asymptotic", tolower(method))
  method_check_b <- stringsim("Bootstrap", tolower(method))
  
  if(method_check_a <= 0.7 & method_check_b <= 0.7) {
    stop("Oops! We are sorry, but we have not developed the method you are asking just yet! How do you feel about the 'Asymptotic' method, or maybe 'Bootstrap'?. If in doubt, you can always check the documentation using ?coeff_lm :)")
    
  } else if(method_check_a > 0.7) {
    method <- "Asymptotic"
    warning("Did you mean 'Asymptotic'? If yes, just roll with it! If no, please disregard the results and begin again! Check ?coeff_lm for documentation")
    
  } else if(method_check_b > 0.7) {
    method <- "Bootstrap"
    warning("Did you mean 'Bootstrap'? If yes, just roll with it! If no, please disregard the results and begin again! Check ?coeff_lm for documentation")
  }
  #--------------------------------------------------------------------------
  
  #
  residual <- Dependent - Independent%*%as.matrix(beta)
  
  #
  sigma_hat <- as.numeric((1/degrees_freedom)*t(residual)%*%residual)
  
  # Estimate of the variance of the estimated beta from Eq. (1.2)
  var_beta <- sigma_hat*solve(t(Independent)%*%Independent)
  
  # CI based on alpha:
  z <- alpha/2
  quad <- 1 - z
  
  if(method == "Asymptotic") {
    
    ci_beta <- c(beta - qnorm(p = quad)*sqrt(var_beta),
                 beta + qnorm(p = quad)*sqrt(var_beta))
    
  } else {
    
    # bootstrap goes here: (Eyoel)
    # define dummy params
    vec <- rep(NA, size)
    allofit <- cbind(Dependent, Independent)
    
    for (i in 1:size) {
      ci_beta <- allofit[sample(1:n, replace = TRUE),]
      vec[i]=mean(ci_beta)
    }
    
    # magnifico !
    
    ci_beta <- quantile(vec, c(quad, z))
    
  }
  
  
  # Return all estimated values
  
  coeff_ci_results <- list(Beta = beta,
                         Sigma = sigma_hat,
                         Variance_Beta = var_beta,
                         Confidence_Interval = ci_beta)
  
  # still missing proper show of CI:
  # results_names <- list("Beta", "Sigma", "Variance", "CI")
  # coeff_lm_results <- cbind(results_names, results)
  
  return(coeff_ci_results)
  
}

```





```{r}
#' @title Linear Model Function-group3
#'
#' @description Function that 
#' @param Dependent A \code{vector} with the values for the dependent variable (also called outcome).
#' @param Independent A \code{matrix} with the values for the independent variable (also called predictors, or explanatory variable).
#' @param Beta A \code{matrix} that can be calculated using \code{coeff_lm} function.!
#' @param alpha A \code{numeric} (double) that sets the alpha coefficient to be used. Has to be between 0 and 1.
#' @param method A \code{string} that defines the method used. Options are "Asymptotic" and "Bootstrap", accepts minor misspellings with a warning - which can be both good and bad.
#' @return A \code{list} containing the following attributes:
#' \describe{
#'      \item{beta}{Estimated coefficients, Linear Regression Model.}
#'      \item{sigma2}{explanation}
#'      \item{variance_beta}{explanation}
#'      \item{ci}{explanation}
#' }
#' @author John M. Musah & Alan R. Galloway
#' @importFrom 
#' @export
#' @examples
#' Using data("USArrests")
#' coeff_lm(USArrests$Murder,USArrests$UrbanPop)

coeff_ftest <- function (Dependent, Independent) {
  
  #--------------------------------------------------------------------------
  #-------------------------------- preamble --------------------------------
  
  # in case user gets something that is not a vector for 'Dependent'
  #  or a matrix for 'Independent', coerce data:
  #  
 Dependent <- as.matrix(Dependent)
 Independent <- as.matrix(cbind(1,Independent))
  #--------------------------------------------------------------------------
  # Define number of observation and dimension:
  # 
  n <- length(Dependent)
  p <- dim(Independent)[2]
  degrees_freedom <- n - p
  beta <- coeff_beta(Dependent, Independent)
  fit <- Independent%*%beta
  sample_mean <- mean(Dependent)
  SSM <- 0
  SSE <- 0
  dSSM <- 0
  dSSE <- 0
  #--------------------------------------------------------------------------
  
  # check and warnings:
  # 
  if(n != dim(Independent)[1])
    
    stop("Can you check the correspondence between x and y values? It seems we do not have proper pairs! If in doubt, check the documentation using ?coeff_least_sq")
  #--------------------------------------------------------------------------
  
  for (i in 1:n) {
    dSSM <- (fit[i] - sample_mean)^2
    dSSE <- (Dependent[i] - fit[i])^2
    SSM <- SSM + dSSM
    SSE <- SSE + dSSE
  }
  
  DFM <- p
  DFE <- n - p
  MSM <- SSM/DFM
  MSE <- SSE/DFE
  
  #The actual F statistics will be computed here
  f_stat <- MSM/MSE
  
  #The stat will be compared to the real one, retrieved from the linear model previously created
  #F_Real_Stat=summary(MainLinRegr)$fstatistic[1]
  #
  # Bootiful:
  #
  f_prob <- pf(f_stat, DFM, DFE, 1)
  f_info <- rbind(f_stat, DFM, DFE, f_prob)
  rownames(f_info) <- c("F Stat: ","Lower DF: ","Higher DF:","P-Value: ")
  return(f_info) 
  
}







```





```{r}
#' @title functon for mean square predicted error-group3
#'
#' @description Function that 
#' @param Dependent A \code{vector} with the values for the dependent variable (also called outcome).
#' @param Independent A \code{matrix} with the values for the independent variable (also called predictors, or explanatory variable).
#' @param Beta A \code{matrix} that can be calculated using \code{coeff_lm} function.!
#' @param alpha A \code{numeric} (double) that sets the alpha coefficient to be used. Has to be between 0 and 1.
#' @param method A \code{string} that defines the method used. Options are "Asymptotic" and "Bootstrap", accepts minor misspellings with a warning - which can be both good and bad.
#' @return A \code{list} containing the following attributes:
#' \describe{
#'      \item{beta}{Estimated coefficients, Linear Regression Model.}
#'      \item{sigma2}{explanation}
#'      \item{variance_beta}{explanation}
#'      \item{ci}{explanation}
#' }
#' @author John M. Musah & Alan R. Galloway
#' @importFrom 
#' @export
#' @examples
#' Using data("USArrests")
#' coeff_lm(USArrests$Murder,USArrests$UrbanPop)


coeff_mspe <- function (Dependent, Independent) {
  
  #--------------------------------------------------------------------------
  #-------------------------------- preamble --------------------------------
  
  # in case user gets something that is not a vector for 'Dependent'
  #  or a matrix for 'Independent', coerce data:
  #  
 Dependent <- as.matrix(Dependent)
 Independent <- as.matrix(cbind(1,Independent))
  #--------------------------------------------------------------------------
  # Define base and dummy parameters:
  # 
  n <- length(Dependent)
  p <- dim(Independent)[2]
  degrees_freedom <- n - p
  beta <- coeff_beta(Dependent, Independent)
  fit <- Independent%*%beta
  sample_mean <- mean(Dependent)
  dMSPE = 0
  MSPE = 0
  #--------------------------------------------------------------------------
  # check and warnings:
  # 
  if(n != dim(Independent)[1])
    
    stop("Can you check the correspondence between x and y values? It seems we do not have proper pairs! If in doubt, check the documentation using ?coeff_least_sq")
  #--------------------------------------------------------------------------
  
  for (i in 1:n) {
    dMSPE <- (Dependent[i]- fit[i])^2
    MSPE = MSPE + dMSPE
  }
  
  MSPE <- n^{-1} * MSPE
  MSPE <- cbind(MSPE)
  
  return(MSPE)
  
}

```





```{r}
#' @title Plot function for coeff lm package-group3
#'
#' @description Function that 
#' @param Dependent A \code{vector} with the values for the dependent variable (also called outcome).
#' @param Independent A \code{matrix} with the values for the independent variable (also called predictors, or explanatory variable).
#' @param Beta A \code{matrix} that can be calculated using \code{coeff_lm} function.!
#' @param alpha A \code{numeric} (double) that sets the alpha coefficient to be used. Has to be between 0 and 1.
#' @param method A \code{string} that defines the method used. Options are "Asymptotic" and "Bootstrap", accepts minor misspellings with a warning - which can be both good and bad.
#' @return A \code{list} containing the following attributes:
#' \describe{
#'      \item{beta}{Estimated coefficients, Linear Regression Model.}
#'      \item{sigma2}{explanation}
#'      \item{variance_beta}{explanation}
#'      \item{ci}{explanation}
#' }
#' @author John M. Musah & Alan R. Galloway
#' @importFrom 
#' @export
#' @examples
#' Using data("USArrests")
#' coeff_lm(USArrests$Murder,USArrests$UrbanPop)
#' 
#' The actual function begins therefrom:




coeff_plot <- function (Dependent, Independent) {
  #--------------------------------------------------------------------------
  #-------------------------------- preamble --------------------------------
  
  # in case user gets something that is not a vector for 'Dependent'
  #  or a matrix for 'Independent', coerce data:
  #  
 Dependent <- as.matrix(Dependent)
 Independent <- as.matrix(cbind(1,Independent))
  #--------------------------------------------------------------------------
  # Define base and dummy parameters:
  # 
  n <- length(Dependent)
  p <- dim(Independent)[2]
  degrees_freedom <- n - p
  ci_beta <- rep(NA, p)
  size <- 1000
  beta <- coeff_beta(Dependent, Independent)
  residual <- Dependent - Independent%*%as.matrix(beta)
  fit <- Independent%*%beta
  #--------------------------------------------------------------------------
  # check and warnings:
  # 
  if(n != dim(Independent)[1])
    
    stop("Can you check the correspondence between x and y values? It seems we do not have proper pairs! If in doubt, check the documentation using ?coeff_least_sq")
  #--------------------------------------------------------------------------
  #
  
  par(mfrow=c(1,3),oma = c(1,0,1,0))
  plot(residual~fit, xlab="Residual Values",ylab="Fitted Values",main="Residuals vs Fitted")
  qqnorm(residual)
  HistResVFit=hist(residual, xlab = "Residual Values", ylab="Frequency")
  title(line = -2)
  
}
```




#Test coeff_beta with lm package

```{r}
data("USArrests")
coeff_beta(USArrests$Murder,USArrests$UrbanPop)
```


```{r}
Model <- lm(USArrests$Murder~ USArrests$UrbanPop)
summary(Model)

```



#REFERENCES
#https://economictheoryblog.com/2016/02/20/rebuild-ols-estimator-manually-in-r/
#https://github.com/andrewc94/Linear-Regression-in-R







#THE R PACKAGE
```{r}

```






















